# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d59ea28d8816d818032e1a3aa78549bc5c142045a11b03663fc1c015e31bff25eb5d3c0e87ae603b638943a494ed4eb0390709d6b65169c9d515059752db43bd

test:
  secret_key_base: 00692623b1e0081dee4fbf7175f428dc382e6992eb120c9cec7036dd2caf1e2b35559e6c825a92d56f4ba4dd51c81517e2815feaf375babefa2f2f4c3e069e29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
